# This file contains all the information to generate a Swagger/OpenAPI
# definition for the cloud_controller_ng V3 API. The OpenAPI definition can
# then be used to generate documentation and many other things for the
# cloud_controller_ng.

name: Cloud Controller NG v3 API
desc: |  # Full markdown intro goes here:
  OpenAPI Specification for a Cloud Foundry Cloud Controller NG server v3 API.
vers: 2.61.0
base: /v3

# API routes:
/apps:
  get: List all apps
  post: Create a new app
/apps/{guid}:
  get: Get an app
  put: Update an app
  patch: Patch an app
  delete: Destroy an app
/apps/{guid}/start:
  put: Start an app
/apps/{guid}/stop:
  put: Stop an app
/apps/{guid}/env:
  get: Get an app environment
/apps/{guid}/droplets/current:
  put: Set current droplet for app
  get: Get current droplet
/processes:
  get: List all processes
/processes/{process_guid}:
  get: Get a process
  patch: Patch a process
/processes/{process_guid}/instances/{index}:
  delete: Terminate a process
/processes/{process_guid}/scale:
  put: Scale a process
/processes/{process_guid}/stats:
  get: Get process statistics
/apps/{app_guid}/processes:
  get: List all processes for an app
/apps/{app_guid}/processes/{type}:
  get: Show process for an app
/apps/{app_guid}/processes/{type}/scale:
  put: Update scale for app process
/apps/{app_guid}/processes/{type}/instances/{index}:
  delete: Terminate process instance for an app
/apps/{app_guid}/processes/{type}/stats:
  get: Get process statistics for an app
/packages:
  get: List all packages
/packages/{guid}:
  get: Show a package
  delete: Destroy a package
/packages/{guid}/upload:
  post: Upload a package
/packages/{guid}/download:
  get: Download a package
/apps/{app_guid}/packages:
  get: List all packages for an app
  post: Create a new package for an app
/packages/{package_guid}/droplets:
  post: Create a new droplet for a package
  get: List droplets for a package
/droplets/{guid}/copy:
  post: Copy a droplet
/droplets:
  get: List all droplets
/droplets/{guid}:
  get: Show a droplet
  delete: Destroy a droplet
/apps/{app_guid}/droplets:
  get: List droplets for an app
/route_mappings:
  post: Create a new route mapping
  get: List all route mappings
/route_mappings/{route_mapping_guid}:
  get: Show a route mapping
  delete: Destroy a route mapping
/apps/{app_guid}/route_mappings:
  get: List all route mappings for an app
/tasks:
  get: List all tasks
/tasks/{task_guid}:
  get: Show a task
/tasks/{task_guid}/cancel:
  put: Cancel a task
/apps/{app_guid}/tasks:
  post: Create a new task for an app
  get: List all tasks for an app
/service_bindings:
  post: Create a new service binding
  get: List all service bindings
/service_bindings/{guid}:
  get: Show a service binding
  delete: Destroy a service binding


# The following section defines all the schema/type information for API
# requests and responses. The format is SchemaType. See http://schematype.org

+listAppsResponse:
  xxx: +str
+getAppResponse:
  xxx: +str
+getAppEnvironmentResponse:
  xxx: +str
+getCurrentDropletResponse:
  xxx: +str
+listProcessesResponse:
  xxx: +str
+getProcessResponse:
  xxx: +str
+getProcessStatisticsResponse:
  xxx: +str
+listProcessesForAppResponse:
  xxx: +str
+showProcessForAppResponse:
  xxx: +str
+getProcessStatisticsForAppResponse:
  xxx: +str
+listPackagesResponse:
  xxx: +str
+showPackageResponse:
  xxx: +str
+downloadPackageResponse:
  xxx: +str
+listPackagesForAppResponse:
  xxx: +str
+listDropletsResponse:
  xxx: +str
+showDropletResponse:
  xxx: +str
+listDropletsForAppResponse:
  xxx: +str
+listDropletsForPackageResponse:
  xxx: +str
+listRouteMappingsResponse:
  xxx: +str
+showRouteMappingResponse:
  xxx: +str
+listRouteMappingsForAppResponse:
  xxx: +str
+listTasksResponse:
  xxx: +str
+showTaskResponse:
  xxx: +str
+listTasksForAppResponse:
  xxx: +str
+showServiceBindingResponse:
  xxx: +str
+listServiceBindingsResponse:
  xxx: +str
